### ISSUE TITLE
Latest release does not have resource just source code.

### ISSUE THREAD

**Issue by DannysRP** [SOH69/mm_radio#11]
I guess the title explains it. The latest update from today doesn't have the mm_radio just the source code so you would have to manually build the UI.

**Comment by DannysRP** [comment]
> Are you using the release version?

Normally I use the zip for mm_radio in releases. I don't build the source myself I just use the one you provide whenever I update but this release doesn't have the resource itself like the other releases it just has the option to download the source code.

**Comment by DannysRP** [comment]
![1](https://github.com/SOH69/mm_radio/assets/88177315/2782cffb-bcf1-4014-8fd9-8102e2e6747b)
![2](https://github.com/SOH69/mm_radio/assets/88177315/b1537586-70c0-407e-b90e-5f7e5b047c26)

v1.7.0 has 'mm_radio' and v1.8.0 does not as the picture shows. Went to test the resource but told me to build the UI or download the release.

**Comment by SOH69** [comment]
Aah fixed it, thats for reporting
