### ISSUE TITLE
No push to talk for radio?

### ISSUE THREAD

**Issue by bluelineparabellum** [SOH69/mm_radio#19]
Deleted qb-radio for this script. Now there is no keybind for push to talk on radio.

**Comment by SOH69** [comment]
Push to Talk is in PMA Voice not my radio script

**Comment by bluelineparabellum** [comment]
> Push to Talk is in PMA Voice not my radio script

Ok for some reason the keybinding is gone after removing qb-radio

**Comment by SOH69** [comment]
Update pma-voice, remove server cache and see if the keybinds work

**Comment by bluelineparabellum** [comment]
> Update pma-voice, remove server cache and see if the keybinds work

Alright. I may see the issue now. I'll update when I can.

**Comment by bluelineparabellum** [comment]
Working!! Awesome. Not an issue with mm-radio!
