### ISSUE TITLE
Channel Members Overlay showing the wrong character names

### ISSUE THREAD

**Issue by ClockworkQueen13** [SOH69/mm_radio#24]
Hello ! Just wanted to report a tiny issue I'm having with mm_radio. It is a beautiful script, but I noticed that whenever you show the overlay for radio members, it shows the names of your other characters. This is problematic as we have people on emergency services speaking on main tac, and it is showing the name of their criminal characters on the overlay instead of the character they are playing. Thank you for your time ! Just figured I would let you know ! :) 

Framework : QB-Core 1.2.6

**Comment by SOH69** [comment]
I m known to this issue, and currently on it
