### ISSUE TITLE
Script Erro OX inv

### ISSUE THREAD

**Issue by TaakoOfficial** [SOH69/mm_radio#25]
We use ox inventory and are getting this error. 

`SCRIPT ERROR: @bl_bridge/imports/client.lua:5: No such export inventory in resource bl_bridge`
![Medal_w2fh1JADEW](https://github.com/SOH69/mm_radio/assets/4751889/d4b319b3-8282-4a82-8206-be2643f87b1f)

I know we use the bridge for something else and it works fine so I'm not sure what's going on

**Comment by SOH69** [comment]
Framework, inventory, ox_lib version using

**Comment by TaakoOfficial** [comment]
QBCore, OX inventory, ox_lib 3.18.0

**Comment by Frowmza** [comment]
> QBCore, OX inventory, ox_lib 3.18.0

when bridge is starting, it should throw and error telling you why

**Comment by TaakoOfficial** [comment]
![chrome_fefAS4eUq9](https://github.com/SOH69/mm_radio/assets/4751889/449f2490-a2cf-4eff-99bb-10e0315f5c54)

**Comment by Frowmza** [comment]
did you follow bridge instrucion?

**Comment by Frowmza** [comment]
see, make sure to read readme before opening any issue!

**Comment by TaakoOfficial** [comment]
Yeah My Convars are set and the script is installed correctly like I statted before we use it for something else

**Comment by SOH69** [comment]
@TaakoOfficial is your issue solved?

**Comment by TaakoOfficial** [comment]
Nope Still getting errors
![Medal_gKMZd1KvOq](https://github.com/SOH69/mm_radio/assets/4751889/0d45c4e0-95a2-462c-b36b-4575d026df3b)

**Comment by Frowmza** [comment]
are u sure you setup the convars well?, seems you setted qb instead of ox in inventory

**Comment by TaakoOfficial** [comment]
![chrome_7WrsjPPRno](https://github.com/SOH69/mm_radio/assets/4751889/12ebc271-270f-4802-b1e2-473a016cd1cf)

**Comment by TaakoOfficial** [comment]
Yeah I'm sure

**Comment by Frowmza** [comment]
send me your bridge init.lua

**Comment by TaakoOfficial** [comment]
`if not lib then return end
local DEFAULT_FRAMEWORK = 'qb'
Framework = setmetatable({}, {
    __newindex = function(self, name, fn)
        exports(name, function() return fn end)
        rawset(self, name, fn)
    end
})

local function format(str)
    if not string.find(str, "'") then return str end
    return str:gsub("'", "")
end

Config = {
    frameworks = {
        ox = false,
        esx = false,
        qb = true,
        nd = false,
        ps = false,
        qs = false
    },
    convars = {
        core = format(GetConvar('bl:framework', DEFAULT_FRAMEWORK)),
        inventory = format(GetConvar('bl:inventory', DEFAULT_FRAMEWORK)),
        context = format(GetConvar('bl:context', DEFAULT_FRAMEWORK)),
        target = format(GetConvar('bl:target', DEFAULT_FRAMEWORK)),
        progressbar = format(GetConvar('bl:progressbar', DEFAULT_FRAMEWORK)),
        radial = format(GetConvar('bl:radial', DEFAULT_FRAMEWORK)),
        notify = format(GetConvar('bl:notify', DEFAULT_FRAMEWORK)),
        textui = format(GetConvar('bl:textui', DEFAULT_FRAMEWORK)),
    },
    resources = {
        inventory = {
            ox = 'ox_inventory',
            qb = 'qb-inventory',
            ps = 'ps-inventory',
            qs = 'qs-inventory'
        },
        core = {
            nd = 'ND_Core',
            qb = 'qb-core',
            esx = 'es_extended'
        },
        context = {
            qb = 'qb-menu',
            ox = 'none'
        },
        progressbar = {
            qb = 'progressbar',
            ox = 'none'
        },
        radial = {
            qb = 'qb-radialmenu',
            ox = 'none'
        },
        target = {
            qb = 'qb-target',
            ox = 'ox_target',
        },
        notify = {
            qb = 'none',
            ox = 'none',
            esx = 'none',
        },
        textui = {
            ox = 'none',
            qb = 'none',
        }
    },

    client = {
        dir = 'client',
        moduleNames = {
            "core",
            "context",
            "target",
            "radial",
            "notify",
            "inventory",
            "progressbar",
            'textui',
        },
        all = {
            inventory = true
        },
    },
    server = {
        dir = 'server',
        moduleNames = {
            "inventory",
            "core",
            "notify",
        },
        alternative = {
            inventory = {
                ps = 'qb',
                qs = 'qb'
            }
        },
    }
}

exports('getFramework', function(module)
    local moduleConfig = Config.resources[module]
    if not moduleConfig then return end
    
    return moduleConfig[Config.convars[module]]
end)

local function loadModule(dir, moduleName, framework)
    local fomartedModule = ("%s.%s.%s"):format(dir, moduleName, framework)
    local success, module = pcall(require, fomartedModule)
    if type(module) ~= "string" or not string.find(module, 'not found') then
        if success then
            Framework[moduleName] = module
            print(("[%s] Loaded module %s"):format(framework, moduleName))
        else
            error(("Error loading module %s: %s"):format(moduleName, module))
        end
    end
end

local modulesConfig = Config[lib.context]

if lib.context == 'server' then
    local UUID = require'utils'.UUID
    lib.callback.register('UUID', function(_, num)
        return UUID(num)
    end)
end

for _, moduleName in ipairs(modulesConfig.moduleNames) do
    local framework = Config.convars[moduleName]
    if Config.frameworks[framework] then
        local hasAlternative = modulesConfig.alternative and modulesConfig.alternative[moduleName]
        local moduleForAll = modulesConfig.all and modulesConfig.all[moduleName] and 'all' or framework
        local alternative = hasAlternative and hasAlternative[moduleForAll] or moduleForAll

        local resourceName = Config.resources[moduleName] and Config.resources[moduleName][framework]

        if not resourceName then
            return error('there is no '..framework.. ' on module '..moduleName.. '!, please make sure you configured your convars on cfg!')
        elseif resourceName == 'none' or GetResourceState(resourceName) == 'started' then
            loadModule(modulesConfig.dir, moduleName, alternative)
        else
            ExecuteCommand('ensure '..resourceName)
            if lib.waitFor(function()
                if GetResourceState(resourceName) == 'started' then
                    return true
                end
            end, ('resource %s is not starting'):format(resourceName), 2000) then
                loadModule(modulesConfig.dir, moduleName, alternative)
            end
        end
    end
end
`

**Comment by Frowmza** [comment]
> ![chrome_fefAS4eUq9](https://private-user-images.githubusercontent.com/4751889/320668836-449f2490-a2cf-4eff-99bb-10e0315f5c54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MTk0MjYsIm5iZiI6MTcxMjYxOTEyNiwicGF0aCI6Ii80NzUxODg5LzMyMDY2ODgzNi00NDlmMjQ5MC1hMmNmLTRlZmYtOTliYi0xMGUwMzE1ZjVjNTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDhUMjMzMjA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDY1NmQ2YTZmNGI4OTMyNWNhMDc3NWNmMDQzYjdkZDgyZjM4OTU1MmNlMzc0MjQ5MWUwZTlhYzBiMjA2OTllZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KHI_7b6b0XJD0F2zrP6fvHSDApUnvoBE9Q7Z4gWCJAA)

why in the hell you have qb-inventory here

**Comment by Frowmza** [comment]
did you restart server

**Comment by TaakoOfficial** [comment]
> did you restart server

Yes


> > ![chrome_fefAS4eUq9](https://private-user-images.githubusercontent.com/4751889/320668836-449f2490-a2cf-4eff-99bb-10e0315f5c54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MTk0MjYsIm5iZiI6MTcxMjYxOTEyNiwicGF0aCI6Ii80NzUxODg5LzMyMDY2ODgzNi00NDlmMjQ5MC1hMmNmLTRlZmYtOTliYi0xMGUwMzE1ZjVjNTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDhUMjMzMjA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDY1NmQ2YTZmNGI4OTMyNWNhMDc3NWNmMDQzYjdkZDgyZjM4OTU1MmNlMzc0MjQ5MWUwZTlhYzBiMjA2OTllZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KHI_7b6b0XJD0F2zrP6fvHSDApUnvoBE9Q7Z4gWCJAA)
> 
> why in the hell you have qb-inventory here and you setted ox
Not sure I follow We use QBcore framework but OX everything else

**Comment by TaakoOfficial** [comment]
![Medal_0goe32b6lL](https://github.com/SOH69/mm_radio/assets/4751889/753944e5-6d43-486e-a9ff-2eb7010b2c91)
Yeah Causing bunch of issues too

**Comment by Frowmza** [comment]
i can help ya further if you came to byte discord

**Comment by TaakoOfficial** [comment]
It's no longer needed, we have found other viable options.
