### ISSUE TITLE
suggestion -- change radio channels via keybinds

### ISSUE THREAD

**Issue by jaylac2000** [SOH69/mm_radio#26]
i have custom radio for qb-core where i can change the channel with keybinds

this looks like a real nice radio to switch to

but can you make it so players can change both full channels up and down along with decimal channels please :D

```
Config.KeyMapping = {
    IncreaseRadioChannel = 'UP',
    DecreaseRadioChannel = 'DOWN',
    IncreaseRadioChannelDecimal = 'LEFT',
    DecreaseRadioChannelDecimal = 'RIGHT'
}
```

I got mine setup using arrow keys but people can self change or remove these keybinds

**Comment by SOH69** [comment]
done with update 2.0.5

**Comment by jaylac2000** [comment]
Thank youuuu Jay😄

**Comment by jaylac2000** [comment]
Thank youuu😄
