### ISSUE TITLE
Suggestion: Radio Types

### ISSUE THREAD

**Issue by Crayons0814** [SOH69/mm_radio#38]
This is an idea I have been playing with and figured that I could share it here to hopefully see it added since I'm not good enough to know how to make it happen myself.

### The Issue
The current UI is one of the best radio interfaces that exist for fivem, but with the UI being similar to that of an APX next smart radio it makes if feel like a police radio, which is great if your a police officer but if your not it can feel odd to be a civilian or criminal in a server and using what feels like a police radio. The remedy would be to have a different UI for civilians and criminals to use, you could try and load another radio script with a different UI but that would lead to compatibility issues.

### The Solution
My Idea is to add radio types, how this would work is that there could be two items. 
One item would the the "PD Radio" which would be the current UI then another item "Walkie Talkie" with a different simple UI.
When someone uses one of the items it opens to corresponding UI and when that UI is used to connect to a channel that radio type is set as the "Active" type, So even if the hotkey to open the radio UI is used it would open the UI that is set as active.

### BONUS
With the introduction of radio types this would allow for more features to be made in the future depending on what someone active radio type is.
**Example 1:** if a jammer is active and someone is using a certain type of radio it could bypass the jamming and still work. 
**Example 2:** Depending on what radio type is used the radio effect quality could change making cheap radio's have worse audio quality.

**Comment by SOH69** [comment]
done with update 2.0.5
