### ISSUE TITLE
hey, is it a problem on the radio side or on the bridge side? I wrote this first to find out

### ISSUE THREAD

**Issue by jesuisjoszi** [SOH69/mm_radio#40]
![image](https://github.com/SOH69/mm_radio/assets/50300794/5a7c953d-5c3e-4d5b-a18b-98fb0b1e2ce2)

**Comment by SOH69** [comment]
which inventory you are using and framework?

**Comment by jesuisjoszi** [comment]
esx, ox_inventory

**Comment by jesuisjoszi** [comment]
![image](https://github.com/SOH69/mm_radio/assets/50300794/e6b492f5-1c58-4e6e-9b57-c589060833b5)

**Comment by SOH69** [comment]
![image](https://github.com/SOH69/mm_radio/assets/70486873/c202b8ec-dd60-4b0d-b3cd-5e0e42e3e5c0)
this export do exist in the latest ox_inventory version

**Comment by jesuisjoszi** [comment]
![image](https://github.com/SOH69/mm_radio/assets/50300794/2889fee1-9e0b-4c8c-ac5e-90be46f98dfc)
I have this export and the latest version

**Comment by SOH69** [comment]
which version of bl_bridge u are using?
![image](https://github.com/SOH69/mm_radio/assets/70486873/24d4bb94-22e4-4c5c-a68f-4a1ef184907c)
do u see this?

**Comment by jesuisjoszi** [comment]
![image](https://github.com/SOH69/mm_radio/assets/50300794/04255ab1-3950-4eaf-940e-4e6bc8b8fdad)
version '1.2.2'

**Comment by jesuisjoszi** [comment]
esx legacy (https://github.com/esx-framework/esx_core)

error when the radio battery dies

**Comment by SOH69** [comment]
please recheck that, if it errors always when u try to open the radio

**Comment by jesuisjoszi** [comment]
no, the error only appears when the radio has zero percent battery

**Comment by jesuisjoszi** [comment]
this is how it works normally

**Comment by SOH69** [comment]
request you to move to discord for better assistance

**Comment by jesuisjoszi** [comment]
hjoszza add

**Comment by SOH69** [comment]
just drop ur issue in support channel of my discord server

**Comment by SOH69** [comment]
@jesuisjoszi will close this issue after 24hr, didn't heard anything from you
