### ISSUE TITLE
Issue with battery

### ISSUE THREAD

**Issue by Hari-Dom** [SOH69/mm_radio#45]
Not able to use the aaa cells to charge the radio and radio not working while turning of the battery system

**Comment by SOH69** [comment]
inv, franework, ox_lib version, radio version using

**Comment by Hari-Dom** [comment]
ox inv, esx framework, ox lib 3.21.0, radio version 2.0.5

**Comment by SOH69** [comment]
Inv, framework version

**Comment by SOH69** [comment]
And error screenshot?

**Comment by Hari-Dom** [comment]
inv version 2.40.1, no errors, even if i disable the charging system the radio shows no charge and if i use aaa cells for charginbg charging doesnt happen,

no errors in f8 console nor the sever console

**Comment by SOH69** [comment]
Enable battery system, and do it again it should throw some error

**Comment by Hari-Dom** [comment]
1.10.5

**Comment by SOH69** [comment]
Fixed with new version release
