### ISSUE TITLE
job check issue (while switching job in-game)

### ISSUE THREAD

**Issue by Harry755** [SOH69/mm_radio#46]
got a job check issue for eg: when you are currently unemployed or police off duty when entered the server and you switched to on duty or changed to police duty and if you try to enter channels which are restricted put given permission for the job then you cant enter the radio 

job check doesnt happen when you switch between jobs ingame

check on this : https://streamable.com/v090wx

**Comment by SOH69** [comment]
inv, franework, ox_lib version, radio version using

**Comment by SOH69** [comment]
Fixed with new version release
