### ISSUE TITLE
Allowed Channels in Jammer

### ISSUE THREAD

**Issue by Jxncsi** [SOH69/mm_radio#48]
The jammer can only add a whole number. e.g.: 15, When I add e.g.: 15.01 the jammer will only allow the 15Mhz channel.

**Comment by SOH69** [comment]
Fixed with commit [cc80b4eb50edf68e3c3f69cd1a30a1b72de0f43a](https://github.com/SOH69/mm_radio/commit/cc80b4eb50edf68e3c3f69cd1a30a1b72de0f43a)
