### ISSUE TITLE
Radio disconnected not

### ISSUE THREAD

**Issue by Dixel-exe** [SOH69/mm_radio#5]
Hello,

Radio does not disconnect when I no longer have the item in the inventory, I can then still continue to radio

I use the qs-inventory

**Comment by SOH69** [comment]
Make sure you are using the latest version

**Comment by Dixel-exe** [comment]
We use the latest version

**Comment by SOH69** [comment]
Actually join my discord so that i can assist furthur, i dont got a qs inventory
