### ISSUE TITLE
Dual Channel

### ISSUE THREAD

**Issue by warrenzky** [SOH69/mm_radio#50]
Hi, I would like to request to have it Dual Channel where you can listen to both channels.
This is helpful with the LEA and Medics to have a Department Radio.
There should be a button where you can switch where to talk, Channel 1 or Channel 2, so you don't have to make another key binds.

PS. I love your radio script by the way. :)

**Comment by ClockworkQueen13** [comment]
I would die for this! I've been looking for a script with that ability all day.

**Comment by SOH69** [comment]
PMA VOICE dont support it, so currently its not possible
