### ISSUE TITLE
2 new function

### ISSUE THREAD

**Issue by Jxncsi** [SOH69/mm_radio#51]
Hi! Can you add to radio the click sound for players when anyone start speak to the radio and can you do to save the battery status after server restart? And add a sound when the battery was 5%. Thanks if you reád and do it.

**Comment by SOH69** [comment]
The click sound comes from pma voice not radio script, so that’s cannot be implemented
Battery system is a calculation, so its impossible to add a alert on low battery, you have to follow it

**Comment by Jxncsi** [comment]
So none of them can be done?

**Comment by Jxncsi** [comment]
And can you do to save the battery level after server restart?

**Comment by 1nexis** [comment]
> Hi! Can you add to radio the click sound for players when anyone start speak to the radio and can you do to save the battery status after server restart? And add a sound when the battery was 5%. Thanks if you reád and do it.

made a pr for the click sounds

**Comment by Jxncsi** [comment]
> > Hi! Can you add to radio the click sound for players when anyone start speak to the radio and can you do to save the battery status after server restart? And add a sound when the battery was 5%. Thanks if you reád and do it.
> 
> made a pr for the click sounds

What do you mean?

**Comment by SOH69** [comment]
Done with release v2.0.7
