### ISSUE TITLE
When radio item is moved from a slot in inventory, it disconnects you from the channel you connect too

### ISSUE THREAD

**Issue by LukeeeChan** [SOH69/mm_radio#9]
The inventory being used is "ps-inventory". Self-explanatory..

**Comment by SOH69** [comment]
Use this [branch](https://github.com/SOH69/mm_radio/tree/ps-inventory)

**Comment by LukeeeChan** [comment]
@SOH69 Page not found.

**Comment by SOH69** [comment]
merged to the [main branch](https://github.com/SOH69/mm_radio)
